### ISSUE TITLE
Fix filterCourses.js

### ISSUE THREAD

**Issue by jhcccc** [Deerhound579/my-exams#11]
![IMG_6778](https://user-images.githubusercontent.com/8275280/75097842-42e81380-557d-11ea-9566-1a9259507c47.JPG)

Right now, filterCourses returns a `Set`:
`[ "COMP 322", "COMP 251", "COMP 273", "COMP 303", "ECSE 321", "COMP 307" ]`

 But It should return **An array of objects**!

The expected output is this ` [{"COURSE NUMBER": "COMP 250", "SECTION": "001"},]` as specified in the code.

**Comment by Deerhound579** [comment]
Fixed. Forgot to push changes.
