### ISSUE TITLE
Dates are not sorted

### ISSUE THREAD

**Issue by jhcccc** [Deerhound579/my-exams#20]
![IMAGE 2020-02-22 23:38:44](https://user-images.githubusercontent.com/8275280/75103724-a3eb0800-55cc-11ea-9aa6-f18b27ae9588.jpg)

Apr 20 - 24 - 27 - 22 ??
Sort the dates!

**Comment by Deerhound579** [comment]
Fixed 411eff2d588b9d7971e3d8242ccccd63d22ba7c3
