### ISSUE TITLE
Update README with more info

### ISSUE THREAD

**Issue by Deerhound579** [Deerhound579/my-exams#21]
* Change pictures to the sorted, correct dates
* Explain conflict modal

**Comment by jhcccc** [comment]
Images for Readme:

![myexams](https://user-images.githubusercontent.com/8275280/75208512-e5ed8880-5749-11ea-8f74-895896210711.png)

**Comment by jhcccc** [comment]
![phone](https://user-images.githubusercontent.com/8275280/75473562-64714280-5963-11ea-9e82-d6a643203599.png)
![laptop](https://user-images.githubusercontent.com/8275280/75473568-6804c980-5963-11ea-8b0f-51bdb05e5b56.png)

**Comment by jhcccc** [comment]
![calendar2](https://user-images.githubusercontent.com/8275280/75474638-56242600-5965-11ea-890f-a858ac412a0c.png)

**Comment by jhcccc** [comment]
<img width="769" alt="conflict" src="https://user-images.githubusercontent.com/8275280/75476961-7eae1f00-5969-11ea-9526-c738c1c4d300.png">

**Comment by jhcccc** [comment]
Regulated Image Width:
<img width="600" alt="conflict" src="https://user-images.githubusercontent.com/8275280/75479550-bd45d880-596d-11ea-9a92-0a2b69f1e03b.png">
![l1](https://user-images.githubusercontent.com/8275280/75479552-bdde6f00-596d-11ea-9d02-217ab5b01631.png)
![l2](https://user-images.githubusercontent.com/8275280/75479554-bdde6f00-596d-11ea-8d63-e6fbf18e6697.png)
![phone](https://user-images.githubusercontent.com/8275280/75479555-be770580-596d-11ea-9284-76700fff1c90.png)

**Comment by jhcccc** [comment]
<img width="600" alt="conflict" src="https://user-images.githubusercontent.com/8275280/75503480-bcc83480-59a3-11ea-917d-72c182b964b6.png">
![l1](https://user-images.githubusercontent.com/8275280/75503481-bcc83480-59a3-11ea-9a47-5ef218fbe118.png)
![l2](https://user-images.githubusercontent.com/8275280/75503483-bd60cb00-59a3-11ea-9afb-fabd716c4e5d.png)
![phone](https://user-images.githubusercontent.com/8275280/75503484-bd60cb00-59a3-11ea-9ea5-5d1132d9d812.png)
