### ISSUE TITLE
Exam Conflict 

### ISSUE THREAD

**Issue by jhcccc** [Deerhound579/my-exams#6]
Text To Show:
[Warning Icon] You have two or more exams at exact same time. Please follow [Conflict Resolve Procedure](https://www.mcgill.ca/exams/dates/conflicts).

UI Component: [Alert](https://next.ant.design/components/alert/)

**Comment by Deerhound579** [comment]
Created warning modal 0cb6ae6bd10f4732ad391e6833e3a0d0c619cbfe
